/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthCamerasIndexRouteImport } from './routes/_auth/cameras/index'
import { Route as AuthCamerasCameraIdRouteImport } from './routes/_auth/cameras/$cameraId'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminRtsRouteImport } from './routes/_auth/admin/rts'
import { Route as AuthAdminDesasRouteImport } from './routes/_auth/admin/desas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCamerasIndexRoute = AuthCamerasIndexRouteImport.update({
  id: '/cameras/',
  path: '/cameras/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCamerasCameraIdRoute = AuthCamerasCameraIdRouteImport.update({
  id: '/cameras/$cameraId',
  path: '/cameras/$cameraId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRtsRoute = AuthAdminRtsRouteImport.update({
  id: '/admin/rts',
  path: '/admin/rts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminDesasRoute = AuthAdminDesasRouteImport.update({
  id: '/admin/desas',
  path: '/admin/desas',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/admin/desas': typeof AuthAdminDesasRoute
  '/admin/rts': typeof AuthAdminRtsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/cameras/$cameraId': typeof AuthCamerasCameraIdRoute
  '/cameras/': typeof AuthCamerasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/': typeof AuthIndexRoute
  '/admin/desas': typeof AuthAdminDesasRoute
  '/admin/rts': typeof AuthAdminRtsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/cameras/$cameraId': typeof AuthCamerasCameraIdRoute
  '/cameras': typeof AuthCamerasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/desas': typeof AuthAdminDesasRoute
  '/_auth/admin/rts': typeof AuthAdminRtsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/cameras/$cameraId': typeof AuthCamerasCameraIdRoute
  '/_auth/cameras/': typeof AuthCamerasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/admin/desas'
    | '/admin/rts'
    | '/admin/users'
    | '/cameras/$cameraId'
    | '/cameras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/admin/desas'
    | '/admin/rts'
    | '/admin/users'
    | '/cameras/$cameraId'
    | '/cameras'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/profile'
    | '/_auth/'
    | '/_auth/admin/desas'
    | '/_auth/admin/rts'
    | '/_auth/admin/users'
    | '/_auth/cameras/$cameraId'
    | '/_auth/cameras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cameras/': {
      id: '/_auth/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof AuthCamerasIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cameras/$cameraId': {
      id: '/_auth/cameras/$cameraId'
      path: '/cameras/$cameraId'
      fullPath: '/cameras/$cameraId'
      preLoaderRoute: typeof AuthCamerasCameraIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/rts': {
      id: '/_auth/admin/rts'
      path: '/admin/rts'
      fullPath: '/admin/rts'
      preLoaderRoute: typeof AuthAdminRtsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/desas': {
      id: '/_auth/admin/desas'
      path: '/admin/desas'
      fullPath: '/admin/desas'
      preLoaderRoute: typeof AuthAdminDesasRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminDesasRoute: typeof AuthAdminDesasRoute
  AuthAdminRtsRoute: typeof AuthAdminRtsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthCamerasCameraIdRoute: typeof AuthCamerasCameraIdRoute
  AuthCamerasIndexRoute: typeof AuthCamerasIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminDesasRoute: AuthAdminDesasRoute,
  AuthAdminRtsRoute: AuthAdminRtsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthCamerasCameraIdRoute: AuthCamerasCameraIdRoute,
  AuthCamerasIndexRoute: AuthCamerasIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
